#!/bin/sh

DAEMON="stallwatch"
PIDFILE="/run/stallwatch.pid"

case "$1" in
start)
	echo -n "Starting $DAEMON: "
	start-stop-daemon -S -q -b -m -p "$PIDFILE" -x /bin/sh -- /usr/sbin/stallwatch && echo OK || echo FAIL
	;;
stop)
	echo -n "Stopping $DAEMON: "
	start-stop-daemon -K -q -p "$PIDFILE" && rm -f "$PIDFILE" && echo OK || echo FAIL
	;;
restart)
	$0 stop
	sleep 1
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
